WestcoastEducationStudentPortal/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using WestcoastEducationStudentPortal.Services;

namespace WestcoastEducationStudentPortal.Controllers
{
    public class CoursesController : Controller
    {
        private readonly CoursesService _service;

        public CoursesController(CoursesService service)
        {
            _service = service;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            return View(await _service.GetAll());
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _service.Get == null)
            {
                return NotFound();
            }

            return View(await _service.Get(id ?? 0));
        }
    }
}

WestcoastEducationStudentPortal/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using WestcoastEducationStudentPortal.Models;
using WestcoastEducationStudentPortal.Services;

namespace WestcoastEducationStudentPortal.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly CoursesService _courseService;
        private readonly StudentsService _studentService;

        public RegistrationController(CoursesService coursesService, StudentsService studentService)
        {
            _courseService = coursesService;
            _studentService = studentService;   
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> RegistrateToCourse(int? id)
        {
            if (id == null || _courseService.Get == null)
            {
                return NotFound();
            }

            return View(new RegistrateStudentModel
            {
                Course = await _courseService.Get(id ?? 0),
                Students = await _studentService.GetAll()
            });
        }

        [HttpPost]
        public async Task<IActionResult> RegistrateStudentToCourse([Bind("Course,CourseId,Student,Students]")] RegistrateStudentModel sci)
        {
            //var courseId = (collection["CourseId"]);
            //var studentId = (collection["StudentId"]);
            if (sci.CourseId == null || sci.Student == null)
            {
                return NotFound();
            }

            //var courseId = collection.CourseId;
            //var studentId = 0;


            await _studentService.RegistrateOnCourse(int.Parse(sci.Student), int.Parse(sci.CourseId));

            var course = await _courseService.Get(int.Parse(sci.CourseId));

            return View(course);
        }
    }
}

WestcoastEducationStudentPortal/Views/Courses/Delete.cshtml
@model WestcoastEducationStudentPortal.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lenght)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lenght)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CourseId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WestcoastEducationStudentPortal/Views/Courses/Details.cshtml
@model WestcoastEducationStudentPortal.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lenght)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lenght)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.CourseId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WestcoastEducationStudentPortal/Views/Courses/Index.cshtml
@model IEnumerable<WestcoastEducationStudentPortal.Models.Course>

@{
    ViewData["Title"] = "Index";
}

<h1>Courses</h1>

<p>
    Here you will find all our available courses.
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lenght)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Details)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lenght)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Details)
            </td>
            <td>
                <a asp-controller="Registration" asp-action="RegistrateToCourse" asp-route-id="@item.CourseId">Registrate</a> |
            </td>
        </tr>
}
    </tbody>
</table>